apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oeapp 
  namespace: argocd 
spec:  
  project: default
  source:
    repoURL: 'https://github.com/prathapxsz/Helm-ArgoCD.git'
    path: ./
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
